[package]
name = "heatmetal"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = true
debug = false
incremental = false
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.15.3"
